modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "valkyrienskies"
version = "${version}"
displayName = "Valkyrien Skies"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.valkyrienskies]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrienskies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"